[profile.default]
src = "src"
out = "out"
libs = ["lib/openzeppelin-contracts", "lib/openzeppelin-contracts-upgradeable/contracts"]

remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]